# Generated by Django 4.1.1 on 2022-12-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planta",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
